[package]
name = "harbor"
version = "0.1.0"
edition = "2018"

[[bin]]
name = "harbor"
src = "src/main.rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
public-ip = "0.2.2"
local-ip-address = "0.4.4"

